<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#sklearn" data-toc-modified-id="sklearn-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>sklearn</a></span><ul class="toc-item"><li><span><a href="#sklearn.feature_extraction.image.extract_patches_2d" data-toc-modified-id="sklearn.feature_extraction.image.extract_patches_2d-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>sklearn.feature_extraction.image.extract_patches_2d</a></span></li><li><span><a href="#sklearn.preprocessing.LabelBinarizer" data-toc-modified-id="sklearn.preprocessing.LabelBinarizer-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>sklearn.preprocessing.LabelBinarizer</a></span></li></ul></li><li><span><a href="#文件读取&amp;字符串匹配" data-toc-modified-id="文件读取&amp;字符串匹配-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>文件读取&amp;字符串匹配</a></span><ul class="toc-item"><li><span><a href="#imutils.paths.list_images()" data-toc-modified-id="imutils.paths.list_images()-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>imutils.paths.list_images()</a></span></li></ul></li><li><span><a href="#os" data-toc-modified-id="os-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>os</a></span><ul class="toc-item"><li><span><a href="#os.walk()" data-toc-modified-id="os.walk()-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>os.walk()</a></span></li><li><span><a href="#os.path.join()" data-toc-modified-id="os.path.join()-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>os.path.join()</a></span></li><li><span><a href="#os.path.sep" data-toc-modified-id="os.path.sep-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>os.path.sep</a></span></li><li><span><a href="#os.path.exists" data-toc-modified-id="os.path.exists-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>os.path.exists</a></span></li></ul></li><li><span><a href="#string" data-toc-modified-id="string-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>string</a></span><ul class="toc-item"><li><span><a href="#str.split()" data-toc-modified-id="str.split()-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>str.split()</a></span></li><li><span><a href="#str.find()" data-toc-modified-id="str.find()-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>str.find()</a></span></li><li><span><a href="#str.rfind()" data-toc-modified-id="str.rfind()-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>str.rfind()</a></span></li><li><span><a href="#str.endswith()" data-toc-modified-id="str.endswith()-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>str.endswith()</a></span></li><li><span><a href="#str.strip()" data-toc-modified-id="str.strip()-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>str.strip()</a></span></li></ul></li><li><span><a href="#字典" data-toc-modified-id="字典-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>字典</a></span><ul class="toc-item"><li><span><a href="#dict.get(key[,-value]-)" data-toc-modified-id="dict.get(key[,-value]-)-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>dict.get(key[, value] )</a></span></li></ul></li></ul></div>

# sklearn 

 ## sklearn.feature_extraction.image.extract_patches_2d 

In [12]:
"""
对图像进行块截取，类比在一张大图像上截图。
>>> from sklearn.feature_extraction import image
>>> one_image = np.arange(16).reshape((4, 4))
>>> one_image
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
>>> patches = image.extract_patches_2d(one_image, (2, 2))
>>> print(patches.shape)
(9, 2, 2)
>>> patches[0]
array([[0, 1],
       [4, 5]])
>>> patches[1]
array([[1, 2],
       [5, 6]])
>>> patches[8]
array([[10, 11],
       [14, 15]])
"""

'\nfrom sklearn.feature_extraction import image\none_image = np.arange(16).reshape((4, 4))\none_image\narray([[ 0,  1,  2,  3],\n       [ 4,  5,  6,  7],\n       [ 8,  9, 10, 11],\n       [12, 13, 14, 15]])\npatches = image.extract_patches_2d(one_image, (2, 2))\nprint(patches.shape)\n(9, 2, 2)\npatches[0]\narray([[0, 1],\n       [4, 5]])\npatches[1]\narray([[1, 2],\n       [5, 6]])\npatches[8]\narray([[10, 11],\n       [14, 15]])\n'

## sklearn.preprocessing.LabelBinarizer

In [2]:
from sklearn.preprocessing import LabelBinarizer

In [4]:
lb = LabelBinarizer()
vector = [1, 2, 6, 4, 2]
lb.fit(vector)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [5]:
lb.classes_

array([1, 2, 4, 6])

In [6]:
# multi-class to ont-hot coding
# fit label binarizer and transform multi-class labels to binary labels.
lb.transform(vector)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

# 文件读取&字符串匹配

## imutils.paths.list_images()

In [18]:
from imutils import paths
imagePath = list(paths.list_images("F:/pyimagesearch/datasets/animals/cats"))

In [20]:
imagePath[:10]

['F:/pyimagesearch/datasets/animals/cats\\cats_00001.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00002.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00003.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00004.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00005.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00006.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00007.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00008.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00009.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00010.jpg']

In [22]:
sorted(imagePath[:10])[::-1]

['F:/pyimagesearch/datasets/animals/cats\\cats_00010.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00009.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00008.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00007.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00006.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00005.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00004.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00003.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00002.jpg',
 'F:/pyimagesearch/datasets/animals/cats\\cats_00001.jpg']

In [2]:
import os

In [12]:
image_types = (".jpg", ".jpeg",".png", ".bmp", ".tif", ".tiff")

def list_files(basePath, validExts=None, contains=None):
    # loop over the directory structure
    for (rooDir, dirNames, filenames) in os.walk(basePath):
        """
        rooDir : 即basePath
        dirName: [所有的目录名]
        filenames: [所有的文件名]
        
        """
        # 遍历所有文件
        for filename in filenames:
            # if the contains string is not None and the filename does not contain the supplied string, the ignore the file
            # 如果我们指定了contains，即所需文件，但没有找到此文件，略过此文件
            if contains is not None and filename.find(contains) == -1:
                continue
            # determine the file extension of the current file
            # 如果此文件是想要的，取的文件的扩展名
            ext = filename[filename.rfind("."):].lower()
            # check to see if the file is an image and should be processed
            if validExts is None or ext.endswith(validExts):
                # contruct the path to the image and yield it
                imagePath = os.path.join(rootDir, filename)
                yield imagePath
def list_image(bathPath, contains=None):
    # return the set of files that are valid
    return list_files(basePath, validExts=image_types, contains=contains)

# os

## os.walk()

In [2]:
import os
help(os.walk)

Help on function walk in module os:

walk(top, topdown=True, onerror=None, followlinks=False)
    Directory tree generator.
    
    For each directory in the directory tree rooted at top (including top
    itself, but excluding '.' and '..'), yields a 3-tuple
    
        dirpath, dirnames, filenames
    
    dirpath is a string, the path to the directory.  dirnames is a list of
    the names of the subdirectories in dirpath (excluding '.' and '..').
    filenames is a list of the names of the non-directory files in dirpath.
    Note that the names in the lists are just names, with no path components.
    To get a full path (which begins with top) to a file or directory in
    dirpath, do os.path.join(dirpath, name).
    
    If optional arg 'topdown' is true or not specified, the triple for a
    directory is generated before the triples for any of its subdirectories
    (directories are generated top down).  If topdown is false, the triple
    for a directory is generated after the 

## os.path.join()

In [13]:
help(os.path.join)

Help on function join in module ntpath:

join(path, *paths)
    # Join two (or more) paths.



In [14]:
os.path.join("home","python","mywork")

'home\\python\\mywork'

## os.path.sep

In [6]:
import os
os.path.sep # 返回操作系统文件路径的分隔符

'\\'

##  os.path.exists

In [4]:
help(os.path.exists) # 判断文件或目录是否存在

Help on function exists in module genericpath:

exists(path)
    Test whether a path exists.  Returns False for broken symbolic links



In [9]:
path1 = "F:/Tensorflow_model/models/research/object_detection/"
path2 = "F:/Tensorflow_model/models/research/object_detection/model_main.py"
print(os.path.exists(path1))
os.path.exists(path2)

True


True

# string


## str.split()

**split()方法以指定分隔符将字符串分开，返回一个包含已分割字符串的列表。**

str.split([separator [, maxsplit]])

* separator:

        可选参数，分隔符，若不指定分隔符，任何空白（空格、换行、制表）即为分割符。
    
* maxsplit:

        可选参数，默认为-1。若指定参数，则返回的列表最多有maxsplit + 1 项。

In [3]:
# 空格和空行都作为分割符
s = 'abcd \n1234\njijo  f\tdwe'
print(s.split())

['abcd', '1234', 'jijo', 'f', 'dwe']


In [9]:
# 原始字符串不会被转义
s2 = r'abcd \n1234\nf\be'
s2.split()

['abcd', '\\n1234\\nf\\be']

In [2]:
text= 'Love thy neighbor'

# splits at space
print(text.split())

grocery = 'Milk, Chicken, Bread'

# splits at ','
print(grocery.split(', '))

# Splitting at ':'
print(grocery.split(':'))

['Love', 'thy', 'neighbor']
['Milk', 'Chicken', 'Bread']
['Milk, Chicken, Bread']


In [3]:
grocery = 'Milk, Chicken, Bread, Butter'

# maxsplit: 2
print(grocery.split(', ', 2))

# maxsplit: 1
print(grocery.split(', ', 1))

# maxsplit: 5
print(grocery.split(', ', 5))

# maxsplit: 0
print(grocery.split(', ', 0))

['Milk', 'Chicken', 'Bread, Butter']
['Milk', 'Chicken, Bread, Butter']
['Milk', 'Chicken', 'Bread', 'Butter']
['Milk, Chicken, Bread, Butter']


## str.find()

In [13]:
help(str.find)

Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



在指定范围内于目标串中找寻是否含有模式串，若有返回第一个模式串出现的下标，若无返回-1

In [1]:
info = 'abca'

print (info.find('a'))    # 从下标0开始，查找在字符串里第一个出现的子串，返回结果：0

print (info.find('a',1))  # 从下标1开始，查找在字符串里第一个出现的子串：返回结果3

print (info.find('3'))    # 查找不到返回-1_

print(info.find('ab23'))


0
3
-1
-1


## str.rfind()

In [30]:
help(str.rfind) # 返回最后一个模式串出现的下标

Help on method_descriptor:

rfind(...)
    S.rfind(sub[, start[, end]]) -> int
    
    Return the highest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



In [31]:
info_2 = "899099"
info_2.rfind('99') 

4

##  str.endswith()

endswith() 方法用于判断字符串是否以指定后缀结尾，如果以指定后缀结尾返回True，否则返回False。可选参数"start"与"end"为检索字符串的开始与结束位置。

In [33]:
Str='Runoob example....wow!!!'
suffix='!!'
print (Str.endswith(suffix))
print (Str.endswith(suffix,20))
suffix='run'
print (Str.endswith(suffix))
print (Str.endswith(suffix, 0, 19))

True
True
False
False


## str.strip()

string.strip([chars])

移除字符串首尾中与chars一样的字符，默认删除首尾的空格。

chars ：可选参数，指定需要删除的字符串

In [7]:
string = ' xoxo love xoxo   '

# Leading whitepsace are removed
print(string.strip())

print(string.strip(' xoxoe'))

# Argument doesn't contain space
# No characters are removed.
print(string.strip('sti'))

string = 'android is awesome'
print(string.strip('an'))

xoxo love xoxo
lov
 xoxo love xoxo   
droid is awesome


# 字典

## dict.get(key[, value] )

get()方法最多接受两个参数。


key: 要查找的键，若此键存在，返回对应的值，不存在返回None。

value：如果要查找的键不存在，返回value。

In [1]:
dic = {"A": 1, "B": 2}
print(dic["A"])
print(dic["C"])

1


KeyError: 'C'

In [10]:
print(dic.get("A"))
print(dic.get("C"))
print(dic.get("C", "C is not in dic"))

1
None
C is not in dic
